version: '3.11'
services:
  dashboard:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=${REDIS_URL-redis://redis:6379}
      - FASTAPI_PORT=${FASTAPI_PORT-8200}
    ports:
      - '${FASTAPI_PORT-8200}:${FASTAPI_PORT-8200}'
    command: ['python', 'app.py']
